--Seguridad 
USE master
ALTER SERVER AUDIT AuditPsycheAI WITH (STATE = ON);

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'M@st3rK3y_PsycheAI_2026!';

CREATE CERTIFICATE CertPsycheAI WITH SUBJECT = 'Certificado TDE PsycheAI';

USE PsycheAI_DB
CREATE DATABASE AUDIT SPECIFICATION AuditSpec_PsycheAI
    FOR SERVER AUDIT AuditPsycheAI
    ADD (SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo BY public),
    ADD (SELECT ON SCHEMA::seguridad BY public),
    ADD (EXECUTE ON SCHEMA::dbo BY public),
    ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
    ADD (DATABASE_PERMISSION_CHANGE_GROUP),
    ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP)
    WITH (STATE = ON);

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'M@st3rK3y_PsycheAI_2026!';

CREATE CERTIFICATE CertPsycheAI WITH SUBJECT = 'Certificado TDE PsycheAI';

CREATE DATABASE ENCRYPTION KEY
    WITH ALGORITHM = AES_256
    ENCRYPTION BY SERVER CERTIFICATE CertPsycheAI;

ALTER DATABASE PsycheAI_DB SET ENCRYPTION ON;